# -*- coding: utf-8 -*-
"""
languages.py - Dil cevirileri / Translations
"""

LANGUAGES = {
    "tr": {
        "name": "Türkçe",
        "flag": "🇹🇷",
        "app_title": "RuntimeFix",
        "trust_line": "✔ Resmi Microsoft Kaynakları\n✔ SHA256 Doğrulandı\n✔ Reklam veya Ek Yazılım Yok",
        "scan_btn":   "🔍  Sorunları Tara",
        "fix_btn":    "🔧  Sorunları Düzelt",
        "cancel_btn": "İptal",
        "about_btn":  "Hakkında",
        "scanning": "Sistem taranıyor…",
        "scan_ok": "✔  Her şey yolunda — eksik bileşen bulunamadı.",
        "scan_missing_1": "⚠  {n} eksik bileşen tespit edildi.",
        "scan_missing_n": "⚠  {n} eksik bileşen tespit edildi.",
        "status_ready": "Hazır. Sistemi taramak için butona tıklayın.",
        "status_ready_msg": "{n} eksik bileşen için bileşen seçip düzelt butonuna tıklayın.",
        "status_all_ok": "✔  Sisteminiz hazır.",
        "status_getting_ready": "Hazırlanıyor…",
        "status_cancelled": "Yükleme iptal edildi.",
        "status_error_summary": "Bazı bileşenler yüklenemedi: {names}. Lütfen tekrar deneyin.",
        "status_failed": "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
        "badge_installed": "Yüklü",
        "badge_missing": "Eksik",
        "nothing_to_do_title": "Bileşen seçilmedi",
        "nothing_to_do_msg": "Lütfen yüklemek istediğiniz bileşenleri seçin.",
        "close_title": "Yükleme Devam Ediyor",
        "close_msg": "Bir yükleme hâlâ devam ediyor. Çıkmak istediğinizden emin misiniz?\n\nYarıda kesmek bazı bileşenlerin eksik kalmasına neden olabilir.",
        "restart_title": "Yeniden Başlatma Gerekli",
        "restart_msg": "<b>Bazı bileşenler yüklemenin tamamlanması için yeniden başlatma gerektiriyor.</b><br><br>Şimdi yeniden başlatabilir veya bilgisayarınızı kullanmaya devam edebilirsiniz.",
        "restart_now": "Şimdi Yeniden Başlat",
        "restart_later": "Sonra Yeniden Başlat",
        "lang_label": "Dil",
        "select_all": "☑  Tümünü Seç",
        "deselect_all": "☐  Tümünü Kaldır",
        "badge_error": "Hata",
        "hdr_log": "Kayıtlar",
        "search_ph": "Ara…",
        "hero_ready": "Durumu görmek için sistemi tarayın",
        "hero_ok": "Sistem tamamen hazır",
        "hero_issues": "Sistem büyük ölçüde hazır",
        "sub_ready": "Tarama birkaç saniye sürer",
        "sub_summary": "{ok} kurulu · {miss} eksik",
        "sub_selected": " · seçili {mb} MB",
        "btn_scan": "Sistemi tara",
        "btn_fix": "Yükle ({n})",
        "btn_select": "Seç",
        "update_avail": "Yeni sürüm mevcut: v{v}",
        "update_btn": "Güncelle",
        "update_title": "Güncelleme",
        "yes": "Evet",
        "no": "Hayır",
        "update_check": "Güncellemeleri Denetle",
        "update_current": "RuntimeFix zaten güncel.\n\nMevcut sürüm: v{v}",
        "update_confirm": "Yeni RuntimeFix sürümü bulundu: v{v}\n\nMevcut sürüm: v{current}\n\nGüncelleme indirilsin ve kurulum başlatılsın mı?\nRuntimeFix indirme tamamlanınca kapanacaktır.",
        "update_no_asset": "v{v} sürümü bulundu ama indirilebilir setup dosyası yok.\n\nGitHub Releases sayfası açılsın mı?",
        "update_downloading": "Güncelleme indiriliyor…",
        "update_starting": "Güncelleme doğrulandı, kurulum başlatılıyor…",
        "update_failed": "Güncelleme işlemi tamamlanamadı.",
        "sel_all2": "Tümünü seç",
        "sel_none2": "Seçimi kaldır",
        "row_installed": "kurulu",
        "row_failed": "hata",
        "row_done": "kuruldu",
        "repair_mode": "Onarım modu",
        "repair_tip": "Kurulu bileşenleri de seçip üzerine yeniden kurmanızı sağlar.\nBozuk runtime'ları onarmak için kullanın.",
        "repair_dlg_text": "Onarım modu, kurulu bileşenleri de seçilebilir hale getirir.\n\nSeçtiğiniz bileşenler kurulu olsalar bile indirilip üzerine yeniden kurulur. Bu işlem bozuk veya eksik dosyalı runtime'ları onarır; programlarınıza ve verilerinize dokunmaz.\n\n\"Her şey kurulu görünüyor ama uygulama/oyun yine hata veriyor\" durumundaysanız bu modu kullanın.",
        "repair_dlg_ok": "Onarım modunu aç",
        "state_on": "Açık",
        "state_off": "Kapalı",
        "row_reinstall": "yeniden kurulacak",
    },
    "en": {
        "name": "English",
        "flag": "🇬🇧",
        "app_title": "RuntimeFix",
        "trust_line": "✔ Official Microsoft Sources\n✔ SHA256 Verified\n✔ No Ads or Bundled Software",
        "scan_btn":   "🔍  Scan for Issues",
        "fix_btn":    "🔧  Fix Issues",
        "cancel_btn": "Cancel",
        "about_btn":  "About",
        "scanning": "Scanning your system…",
        "scan_ok": "✔  Everything looks good — no missing components detected.",
        "scan_missing_1": "⚠  {n} missing component detected.",
        "scan_missing_n": "⚠  {n} missing components detected.",
        "status_ready": "Ready. Click the button to scan your system.",
        "status_ready_msg": "Select components and click Fix to install {n} missing items.",
        "status_all_ok": "✔  Your system is ready.",
        "status_getting_ready": "Getting things ready…",
        "status_cancelled": "Installation was cancelled.",
        "status_error_summary": "Some components could not be installed: {names}. Please try again.",
        "status_failed": "Something went wrong. Please try again.",
        "badge_installed": "Installed",
        "badge_missing": "Missing",
        "nothing_to_do_title": "No components selected",
        "nothing_to_do_msg": "Please select the components you want to install.",
        "close_title": "Installation In Progress",
        "close_msg": "An installation is still running. Are you sure you want to exit?\n\nCancelling mid-install may leave some components partially installed.",
        "restart_title": "Restart Required",
        "restart_msg": "<b>Some components require a restart to fully complete installation.</b><br><br>You can restart now or continue using your PC and restart later.",
        "restart_now": "Restart Now",
        "restart_later": "Restart Later",
        "lang_label": "Language",
        "select_all": "☑  Select All",
        "deselect_all": "☐  Deselect All",
        "badge_error": "Error",
        "hdr_log": "Log",
        "search_ph": "Search…",
        "hero_ready": "Scan your system to see its status",
        "hero_ok": "System is fully ready",
        "hero_issues": "System is mostly ready",
        "sub_ready": "Scanning takes a few seconds",
        "sub_summary": "{ok} installed · {miss} missing",
        "sub_selected": " · selected {mb} MB",
        "btn_scan": "Scan system",
        "btn_fix": "Install ({n})",
        "btn_select": "Select",
        "update_avail": "New version available: v{v}",
        "update_btn": "Update",
        "update_title": "Update",
        "yes": "Yes",
        "no": "No",
        "update_check": "Check for Updates",
        "update_current": "RuntimeFix is already up to date.\n\nCurrent version: v{v}",
        "update_confirm": "A new RuntimeFix version is available: v{v}\n\nCurrent version: v{current}\n\nDownload the update and start setup?\nRuntimeFix will close when the download is complete.",
        "update_no_asset": "Version v{v} is available, but it has no downloadable setup file.\n\nOpen GitHub Releases?",
        "update_downloading": "Downloading update…",
        "update_starting": "Update verified, starting setup…",
        "update_failed": "The update could not be completed.",
        "sel_all2": "Select all",
        "sel_none2": "Clear selection",
        "row_installed": "installed",
        "row_failed": "failed",
        "row_done": "installed",
        "repair_mode": "Repair mode",
        "repair_tip": "Lets you select installed components and reinstall them in place.\nUse this to fix corrupted runtimes.",
        "repair_dlg_text": "Repair mode makes installed components selectable as well.\n\nSelected components will be downloaded and reinstalled over the existing installation, even if they are already installed. This repairs corrupted runtimes; your programs and data are not affected.\n\nUse this when everything looks installed but an app or game still fails.",
        "repair_dlg_ok": "Enable repair mode",
        "state_on": "On",
        "state_off": "Off",
        "row_reinstall": "will reinstall",
    },
    "de": {
        "name": "Deutsch",
        "flag": "🇩🇪",
        "app_title": "RuntimeFix",
        "trust_line": "✔ Offizielle Microsoft-Quellen\n✔ SHA256 verifiziert\n✔ Keine Werbung oder Zusatzsoftware",
        "scan_btn":   "🔍  System scannen",
        "fix_btn":    "🔧  Probleme beheben",
        "cancel_btn": "Abbrechen",
        "about_btn":  "Info",
        "scanning": "System wird gescannt…",
        "scan_ok": "✔  Alles in Ordnung — keine fehlenden Komponenten gefunden.",
        "scan_missing_1": "⚠  {n} fehlende Komponente erkannt.",
        "scan_missing_n": "⚠  {n} fehlende Komponenten erkannt.",
        "status_ready": "Bereit. Klicken Sie zum Scannen.",
        "status_ready_msg": "Komponenten auswählen und auf Beheben klicken ({n} fehlend).",
        "status_all_ok": "✔  Ihr System ist bereit.",
        "status_getting_ready": "Wird vorbereitet…",
        "status_cancelled": "Installation abgebrochen.",
        "status_error_summary": "Einige Komponenten konnten nicht installiert werden: {names}. Bitte erneut versuchen.",
        "status_failed": "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
        "badge_installed": "Installiert",
        "badge_missing": "Fehlend",
        "nothing_to_do_title": "Keine Auswahl",
        "nothing_to_do_msg": "Bitte wählen Sie die Komponenten aus, die Sie installieren möchten.",
        "close_title": "Installation läuft noch",
        "close_msg": "Eine Installation läuft noch. Sind Sie sicher, dass Sie beenden möchten?\n\nEin Abbruch kann dazu führen, dass Komponenten unvollständig installiert bleiben.",
        "restart_title": "Neustart erforderlich",
        "restart_msg": "<b>Einige Komponenten erfordern einen Neustart, um die Installation abzuschließen.</b><br><br>Sie können jetzt neu starten oder Ihren PC weiter verwenden.",
        "restart_now": "Jetzt neu starten",
        "restart_later": "Später neu starten",
        "lang_label": "Sprache",
        "select_all": "☑  Alle auswählen",
        "deselect_all": "☐  Alle abwählen",
        "badge_error": "Fehler",
        "hdr_log": "Protokoll",
        "search_ph": "Suchen…",
        "hero_ready": "System scannen, um den Status zu sehen",
        "hero_ok": "System vollständig bereit",
        "hero_issues": "System größtenteils bereit",
        "sub_ready": "Der Scan dauert wenige Sekunden",
        "sub_summary": "{ok} installiert · {miss} fehlend",
        "sub_selected": " · ausgewählt {mb} MB",
        "btn_scan": "System scannen",
        "btn_fix": "Installieren ({n})",
        "btn_select": "Auswählen",
        "update_avail": "Neue Version verfügbar: v{v}",
        "update_btn": "Aktualisieren",
        "update_title": "Aktualisierung",
        "yes": "Ja",
        "no": "Nein",
        "update_check": "Nach Aktualisierungen suchen",
        "update_current": "RuntimeFix ist bereits aktuell.\n\nAktuelle Version: v{v}",
        "update_confirm": "Eine neue RuntimeFix-Version ist verfügbar: v{v}\n\nAktuelle Version: v{current}\n\nAktualisierung herunterladen und Setup starten?\nRuntimeFix wird nach dem Download geschlossen.",
        "update_no_asset": "Version v{v} ist verfügbar, enthält aber keine Setup-Datei.\n\nGitHub Releases öffnen?",
        "update_downloading": "Aktualisierung wird heruntergeladen…",
        "update_starting": "Aktualisierung geprüft, Setup wird gestartet…",
        "update_failed": "Die Aktualisierung konnte nicht abgeschlossen werden.",
        "sel_all2": "Alle auswählen",
        "sel_none2": "Auswahl aufheben",
        "row_installed": "installiert",
        "row_failed": "Fehler",
        "row_done": "installiert",
        "repair_mode": "Reparaturmodus",
        "repair_tip": "Erlaubt es, installierte Komponenten auszuwählen und neu zu installieren.\nNützlich zur Reparatur beschädigter Runtimes.",
        "repair_dlg_text": "Der Reparaturmodus macht auch installierte Komponenten auswählbar.\n\nAusgewählte Komponenten werden heruntergeladen und über die bestehende Installation neu installiert. Das repariert beschädigte Runtimes; Ihre Programme und Daten bleiben unberührt.\n\nNutzen Sie diesen Modus, wenn alles installiert aussieht, eine Anwendung aber weiterhin Fehler meldet.",
        "repair_dlg_ok": "Reparaturmodus aktivieren",
        "state_on": "Ein",
        "state_off": "Aus",
        "row_reinstall": "wird neu installiert",
    },
    "fr": {
        "name": "Français",
        "flag": "🇫🇷",
        "app_title": "RuntimeFix",
        "trust_line": "✔ Sources Microsoft officielles\n✔ Vérifié SHA256\n✔ Aucune publicité ni logiciel groupé",
        "scan_btn":   "🔍  Analyser",
        "fix_btn":    "🔧  Corriger",
        "cancel_btn": "Annuler",
        "about_btn":  "À propos",
        "scanning": "Analyse du système en cours…",
        "scan_ok": "✔  Tout va bien — aucun composant manquant détecté.",
        "scan_missing_1": "⚠  {n} composant manquant détecté.",
        "scan_missing_n": "⚠  {n} composants manquants détectés.",
        "status_ready": "Prêt. Cliquez pour analyser votre système.",
        "status_ready_msg": "Sélectionnez les composants et cliquez sur Corriger ({n} manquants).",
        "status_all_ok": "✔  Votre système est prêt.",
        "status_getting_ready": "Préparation en cours…",
        "status_cancelled": "Installation annulée.",
        "status_error_summary": "Certains composants n'ont pas pu être installés : {names}. Veuillez réessayer.",
        "status_failed": "Une erreur s'est produite. Veuillez réessayer.",
        "badge_installed": "Installé",
        "badge_missing": "Manquant",
        "nothing_to_do_title": "Aucune sélection",
        "nothing_to_do_msg": "Veuillez sélectionner les composants à installer.",
        "close_title": "Installation en cours",
        "close_msg": "Une installation est toujours en cours. Voulez-vous vraiment quitter ?\n\nL'annulation peut laisser certains composants partiellement installés.",
        "restart_title": "Redémarrage requis",
        "restart_msg": "<b>Certains composants nécessitent un redémarrage pour finaliser l'installation.</b><br><br>Vous pouvez redémarrer maintenant ou continuer à utiliser votre PC.",
        "restart_now": "Redémarrer maintenant",
        "restart_later": "Redémarrer plus tard",
        "lang_label": "Langue",
        "select_all": "☑  Tout sélectionner",
        "deselect_all": "☐  Tout désélectionner",
        "badge_error": "Erreur",
        "hdr_log": "Journal",
        "search_ph": "Rechercher…",
        "hero_ready": "Analysez le système pour voir son état",
        "hero_ok": "Système entièrement prêt",
        "hero_issues": "Système presque prêt",
        "sub_ready": "L'analyse prend quelques secondes",
        "sub_summary": "{ok} installés · {miss} manquants",
        "sub_selected": " · sélection {mb} Mo",
        "btn_scan": "Analyser le système",
        "btn_fix": "Installer ({n})",
        "btn_select": "Sélectionner",
        "update_avail": "Nouvelle version disponible : v{v}",
        "update_btn": "Mettre à jour",
        "update_title": "Mise à jour",
        "yes": "Oui",
        "no": "Non",
        "update_check": "Rechercher des mises à jour",
        "update_current": "RuntimeFix est déjà à jour.\n\nVersion actuelle : v{v}",
        "update_confirm": "Une nouvelle version de RuntimeFix est disponible : v{v}\n\nVersion actuelle : v{current}\n\nTélécharger la mise à jour et lancer l'installation ?\nRuntimeFix se fermera une fois le téléchargement terminé.",
        "update_no_asset": "La version v{v} est disponible, mais sans programme d'installation.\n\nOuvrir GitHub Releases ?",
        "update_downloading": "Téléchargement de la mise à jour…",
        "update_starting": "Mise à jour vérifiée, lancement de l'installation…",
        "update_failed": "La mise à jour n'a pas pu être terminée.",
        "sel_all2": "Tout sélectionner",
        "sel_none2": "Effacer la sélection",
        "row_installed": "installé",
        "row_failed": "erreur",
        "row_done": "installé",
        "repair_mode": "Mode réparation",
        "repair_tip": "Permet de sélectionner des composants installés et de les réinstaller.\nUtile pour réparer des runtimes corrompus.",
        "repair_dlg_text": "Le mode réparation rend également sélectionnables les composants installés.\n\nLes composants sélectionnés seront téléchargés et réinstallés par-dessus l'installation existante. Cela répare les runtimes corrompus ; vos programmes et données ne sont pas affectés.\n\nUtilisez ce mode si tout semble installé mais qu'une application affiche encore des erreurs.",
        "repair_dlg_ok": "Activer le mode réparation",
        "state_on": "Actif",
        "state_off": "Inactif",
        "row_reinstall": "sera réinstallé",
    },
    "es": {
        "name": "Español",
        "flag": "🇪🇸",
        "app_title": "RuntimeFix",
        "trust_line": "✔ Fuentes oficiales de Microsoft\n✔ Verificado SHA256\n✔ Sin anuncios ni software adicional",
        "scan_btn":   "🔍  Analizar",
        "fix_btn":    "🔧  Corregir",
        "cancel_btn": "Cancelar",
        "about_btn":  "Acerca de",
        "scanning": "Analizando el sistema…",
        "scan_ok": "✔  Todo está bien — no se detectaron componentes faltantes.",
        "scan_missing_1": "⚠  Se detectó {n} componente faltante.",
        "scan_missing_n": "⚠  Se detectaron {n} componentes faltantes.",
        "status_ready": "Listo. Haga clic para analizar el sistema.",
        "status_ready_msg": "Seleccione componentes y haga clic en Corregir ({n} faltantes).",
        "status_all_ok": "✔  Su sistema está listo.",
        "status_getting_ready": "Preparando…",
        "status_cancelled": "Instalación cancelada.",
        "status_error_summary": "Algunos componentes no pudieron instalarse: {names}. Por favor, inténtelo de nuevo.",
        "status_failed": "Algo salió mal. Por favor, inténtelo de nuevo.",
        "badge_installed": "Instalado",
        "badge_missing": "Faltante",
        "nothing_to_do_title": "Sin selección",
        "nothing_to_do_msg": "Por favor, seleccione los componentes que desea instalar.",
        "close_title": "Instalación en progreso",
        "close_msg": "Una instalación aún está en curso. ¿Está seguro de que desea salir?\n\nCancelar puede dejar algunos componentes parcialmente instalados.",
        "restart_title": "Reinicio requerido",
        "restart_msg": "<b>Algunos componentes requieren reinicio para completar la instalación.</b><br><br>Puede reiniciar ahora o seguir usando su PC.",
        "restart_now": "Reiniciar ahora",
        "restart_later": "Reiniciar más tarde",
        "lang_label": "Idioma",
        "select_all": "☑  Seleccionar todo",
        "deselect_all": "☐  Deseleccionar todo",
        "badge_error": "Error",
        "hdr_log": "Registro",
        "search_ph": "Buscar…",
        "hero_ready": "Analice el sistema para ver su estado",
        "hero_ok": "Sistema completamente listo",
        "hero_issues": "Sistema casi listo",
        "sub_ready": "El análisis tarda unos segundos",
        "sub_summary": "{ok} instalados · {miss} faltantes",
        "sub_selected": " · selección {mb} MB",
        "btn_scan": "Analizar sistema",
        "btn_fix": "Instalar ({n})",
        "btn_select": "Seleccionar",
        "update_avail": "Nueva versión disponible: v{v}",
        "update_btn": "Actualizar",
        "update_title": "Actualización",
        "yes": "Sí",
        "no": "No",
        "update_check": "Buscar actualizaciones",
        "update_current": "RuntimeFix ya está actualizado.\n\nVersión actual: v{v}",
        "update_confirm": "Hay una nueva versión de RuntimeFix: v{v}\n\nVersión actual: v{current}\n\n¿Descargar la actualización e iniciar el instalador?\nRuntimeFix se cerrará cuando termine la descarga.",
        "update_no_asset": "La versión v{v} está disponible, pero no incluye instalador.\n\n¿Abrir GitHub Releases?",
        "update_downloading": "Descargando actualización…",
        "update_starting": "Actualización verificada, iniciando el instalador…",
        "update_failed": "No se pudo completar la actualización.",
        "sel_all2": "Seleccionar todo",
        "sel_none2": "Quitar selección",
        "row_installed": "instalado",
        "row_failed": "error",
        "row_done": "instalado",
        "repair_mode": "Modo reparación",
        "repair_tip": "Permite seleccionar componentes instalados y reinstalarlos.\nÚtil para reparar runtimes dañados.",
        "repair_dlg_text": "El modo reparación también permite seleccionar componentes instalados.\n\nLos componentes seleccionados se descargarán y reinstalarán sobre la instalación existente. Esto repara runtimes dañados; sus programas y datos no se ven afectados.\n\nUse este modo si todo parece instalado pero una aplicación sigue fallando.",
        "repair_dlg_ok": "Activar modo reparación",
        "state_on": "Activo",
        "state_off": "Inactivo",
        "row_reinstall": "se reinstalará",
    },
}

LANG_ORDER = ["tr", "en", "de", "fr", "es"]

def get(lang_code: str, key: str, **kwargs) -> str:
    lang = LANGUAGES.get(lang_code, LANGUAGES["en"])
    text = lang.get(key, LANGUAGES["en"].get(key, key))
    if kwargs:
        text = text.format(**kwargs)
    return text
